### ISSUE TITLE
Memory leak causing nodes to fail after a period of time.

### ISSUE THREAD

**Issue by Xela101** [catalyst-network/Catalyst#1183]
Memory leak in the node causing it to crash after a period of time.

**Comment by Xela101** [comment]
```07:02:43 [DBG] (ubuntu/3735) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/9625) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/8753) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/6136) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/9352) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/2473) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/4272) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [VRB] (ubuntu/90) Trying to retrieve latest delta as of 03/17/2020 07:02:43 (Catalyst.Core.Modules.Consensus.Deltas.DeltaHashProvider)
07:02:43 [DBG] (ubuntu/90) Current delta production phase "Campaigning : Producing @ 2020-03-17T07:02:43.2511847Z | bafybwifjlh3kaxvsonzurtmg73gr5b2scugyotzv5p7wnfulm4ym7j2owm" (Catalyst.Core.Modules.Consensus.Cycle.CycleEventsProvider)
07:02:43 [VRB] (ubuntu/90) Trying to retrieve latest delta as of 03/17/2020 07:02:43 (Catalyst.Core.Modules.Consensus.Deltas.DeltaHashProvider)
07:02:43 [DBG] (ubuntu/90) Current delta production phase "Campaigning : Idle @ 2020-03-17T07:02:43.2517567Z | bafybwifjlh3kaxvsonzurtmg73gr5b2scugyotzv5p7wnfulm4ym7j2owm" (Catalyst.Core.Modules.Consensus.Cycle.CycleEventsProvider)
07:02:43 [DBG] (ubuntu/1320) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/764) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [DBG] (ubuntu/4253) Finding network interfaces (Makaretu.Dns.MulticastService)
07:02:43 [VRB] (ubuntu/98) Trying to retrieve latest delta as of 03/17/2020 07:02:43 (Catalyst.Core.Modules.Consensus.Deltas.DeltaHashProvider)
07:02:43 [DBG] (ubuntu/98) Current delta production phase "Construction : Idle @ 2020-03-17T07:02:43.2560066Z | bafybwifjlh3kaxvsonzurtmg73gr5b2scugyotzv5p7wnfulm4ym7j2owm" (Catalyst.Core.Modules.Consensus.Cycle.CycleEventsProvider)
07:02:43 [ERR] (ubuntu/4253) FindNics failed (Makaretu.Dns.MulticastService)
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions)
   at System.Net.NetworkInformation.NetworkChange.CreateSocket()
   at System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged(NetworkAddressChangedEventHandler value)
   at Makaretu.Dns.MulticastService.FindNetworkInterfaces()```
